
from grammars.base import GrammarSpec


# based on: https://www.liquid-technologies.com/Reference/Glossary/XML_EBNF1.1.html

base_nonterminal_str = r"""
root ::= prolog element MiscRec | prolog element MiscRec T77
MiscRec ::= "" | Misc MiscRec
prolog ::= XMLDecl MiscRec OptDoctypeDecl
OptDoctypeDecl ::= "" | doctypedecl MiscRec
Misc ::= Comment | PI | T0
XMLDecl ::= T22 VersionInfo OptEncodingDecl OptSDDecl OptS T17
OptEncodingDecl ::= "" | EncodingDecl
OptSDDecl ::= "" | SDDecl
OptS ::= "" | T0
VersionInfo ::= T0 T23 Eq DQVersionNum | T0 T23 Eq SQVersionNum
DQVersionNum ::= T4 T24 T4
SQVersionNum ::= T3 T24 T3
Eq ::= T8
EncodingDecl ::= T0 T25 Eq DQEncName | T0 T25 Eq SQEncName
DQEncName ::= T4 T26 T4
SQEncName ::= T3 T26 T3
SDDecl ::= T0 T27 Eq DQStandalone | T0 T27 Eq SQStandalone
DQStandalone ::= T4 T28 T4 | T4 T29 T4
SQStandalone ::= T3 T28 T3 | T3 T29 T3
doctypedecl ::= T30 T0 Name OptSExternalID OptS OptIntSubsetBlock T10
OptSExternalID ::= "" | T0 ExternalID
OptIntSubsetBlock ::= "" | T31 intSubset T32 OptS
intSubset ::= intSubsetRec
intSubsetRec ::= "" | markupdecl intSubsetRec | DeclSep intSubsetRec
DeclSep ::= PEReference | T0
markupdecl ::= elementdecl | AttlistDecl | EntityDecl | NotationDecl | PI | Comment
extSubset ::= OptTextDecl extSubsetDecl
OptTextDecl ::= "" | TextDecl
extSubsetDecl ::= extSubsetDeclRec
extSubsetDeclRec ::= "" | markupdecl extSubsetDeclRec | DeclSep extSubsetDeclRec
element ::= EmptyElemTag | STag content ETag
STag ::= T9 Name STagRec T10
STagRec ::= "" | T0 Attribute STagRec
Attribute ::= Name Eq AttValue
ETag ::= T11 Name T10
content ::= OptCharData contentRec
OptCharData ::= "" | CharData
contentRec ::= "" | element OptCharData contentRec | Reference OptCharData contentRec | CDSect OptCharData contentRec | PI OptCharData contentRec | Comment OptCharData contentRec
EmptyElemTag ::= T9 Name STagRec T12
Name ::= T1
Nmtoken ::= T2
EntityValue ::= DQEntityValue | SQEntityValue
DQEntityValue ::= T4 DQEntityValueRec T4
DQEntityValueRec ::= "" | T75 DQEntityValueRec | PEReference DQEntityValueRec | Reference DQEntityValueRec
SQEntityValue ::= T3 SQEntityValueRec T3
SQEntityValueRec ::= "" | T76 SQEntityValueRec | PEReference SQEntityValueRec | Reference SQEntityValueRec
AttValue ::= DQAttValue | SQAttValue
DQAttValue ::= T4 DQAttValueRec T4
DQAttValueRec ::= "" | T5 DQAttValueRec | Reference DQAttValueRec
SQAttValue ::= T3 SQAttValueRec T3
SQAttValueRec ::= "" | T6 SQAttValueRec | Reference SQAttValueRec
SystemLiteral ::= DQSystemLiteral | SQSystemLiteral
DQSystemLiteral ::= T4 T65 T4
SQSystemLiteral ::= T3 T66 T3
PubidLiteral ::= DQPubidLiteral | SQPubidLiteral
DQPubidLiteral ::= T4 T67 T4
SQPubidLiteral ::= T3 T68 T3
CharData ::= T7
Comment ::= T13 T15 T14
PI ::= T16 PITarget OptPIBody T17
PITarget ::= Name
OptPIBody ::= "" | T0 T18
CDSect ::= T19 CData T20
CData ::= T21
CharRef ::= T36
Reference ::= EntityRef | CharRef
EntityRef ::= T34 Name T35
PEReference ::= T33 Name T35
elementdecl ::= T37 T0 Name T0 contentspec T10
contentspec ::= T38 | T39 | Mixed | children
children ::= childrenBase OptQuantifier
childrenBase ::= choice | seq
OptQuantifier ::= "" | T44 | T45 | T46
cp ::= cpBase OptQuantifier
cpBase ::= Name | choice | seq
choice ::= T40 OptS cp choiceRec OptS T41
choiceRec ::= OptS T42 OptS cp | OptS T42 OptS cp choiceRec
seq ::= T40 OptS cp seqRec OptS T41
seqRec ::= "" | OptS T43 OptS cp seqRec
Mixed ::= T40 OptS T47 MixedNameRec OptS T48 | T40 OptS T47 OptS T41
MixedNameRec ::= "" | OptS T42 OptS Name MixedNameRec
AttlistDecl ::= T49 T0 Name AttDefRec T10
AttDefRec ::= "" | AttDef AttDefRec
AttDef ::= T0 Name T0 AttType T0 DefaultDecl
AttType ::= StringType | TokenizedType | EnumeratedType
StringType ::= T50
TokenizedType ::= T53 | T52 | T51 | T55 | T54 | T57 | T56
EnumeratedType ::= NotationType | Enumeration
NotationType ::= T58 T0 T40 OptS Name NotationNameRec OptS T41
NotationNameRec ::= "" | OptS T42 OptS Name NotationNameRec
Enumeration ::= T40 OptS Nmtoken EnumRec OptS T41
EnumRec ::= "" | OptS T42 OptS Nmtoken EnumRec
DefaultDecl ::= T59 | T60 | OptFixed AttValue
OptFixed ::= "" | T61 T0
EntityDecl ::= GEDecl | PEDecl
GEDecl ::= T62 T0 Name T0 EntityDef T10
PEDecl ::= T62 T0 T33 T0 Name T0 PEDef T10
EntityDef ::= EntityValue | ExternalID OptNDataDecl
OptNDataDecl ::= "" | NDataDecl
PEDef ::= EntityValue | ExternalID
ExternalID ::= T63 T0 SystemLiteral | T64 T0 PubidLiteral T0 SystemLiteral
NDataDecl ::= T0 T69 T0 Name
TextDecl ::= T22 OptVersionInfo EncodingDecl OptS T17
OptVersionInfo ::= "" | VersionInfo
NotationDecl ::= T70 T0 Name T0 NotationDeclID T10
NotationDeclID ::= ExternalID | PublicID
PublicID ::= T64 T0 PubidLiteral
""".strip()
xgrammar_terminal_str = r"""
T0 ::= [ \t\n\r]+
T1 ::= [:_A-Za-z] [:_A-Za-z0-9\.\-]*
T2 ::= [:_A-Za-z0-9\.\-]+
T3 ::= "'"
T4 ::= "\""
T5 ::= [^<&"]
T6 ::= [^<&']
T7 ::= (("]]" [^>]) | [^<&])*
T8 ::= [ \t\n\r]? "=" [ \t\n\r]?
T9 ::= "<"
T10 ::= [ \t\n\r]? ">"
T11 ::= "</"
T12 ::= [ \t\n\r]? "/>"
T13 ::= "<!--"
T14 ::= "-->"
T15 ::= ([^\-] | "-" [^\-])*
T16 ::= "<?"
T17 ::= "?>"
T18 ::= ("?" [^>] | [^?])*
T19 ::= "<![CDATA["
T20 ::= "]]>"
T21 ::= (("]]" [^>]) | [^\]])*
T22 ::= "<?xml"
T23 ::= "version"
T24 ::= "1.1"
T25 ::= "encoding"
T26 ::= [A-Za-z] [A-Za-z0-9._\-]*
T27 ::= "standalone"
T28 ::= "yes"
T29 ::= "no"
T30 ::= "<!DOCTYPE"
T31 ::= "["
T32 ::= "]"
T33 ::= "%"
T34 ::= "&"
T35 ::= ";"
T36 ::= ("&#" [0-9]+ ";") | ("&#x" [0-9a-fA-F]+ ";")
T37 ::= "<!ELEMENT"
T38 ::= "EMPTY"
T39 ::= "ANY"
T40 ::= "("
T41 ::= ")"
T42 ::= "|"
T43 ::= ","
T44 ::= "?"
T45 ::= "*"
T46 ::= "+"
T47 ::= "#PCDATA"
T48 ::= ")*"
T49 ::= "<!ATTLIST"
T50 ::= "CDATA"
T51 ::= "ID"
T52 ::= "IDREF"
T53 ::= "IDREFS"
T54 ::= "ENTITY"
T55 ::= "ENTITIES"
T56 ::= "NMTOKEN"
T57 ::= "NMTOKENS"
T58 ::= "NOTATION"
T59 ::= "#REQUIRED"
T60 ::= "#IMPLIED"
T61 ::= "#FIXED"
T62 ::= "<!ENTITY"
T63 ::= "SYSTEM"
T64 ::= "PUBLIC"
T65 ::= [^"]*
T66 ::= [^']*
T67 ::= [ \r\na-zA-Z0-9\-'()+,./:=?;!*#@$_%]*
T68 ::= [ \r\na-zA-Z0-9\-()+,./:=?;!*#@$_%]*
T69 ::= "NDATA"
T70 ::= "<!NOTATION"
T75 ::= [^%&"]
T76 ::= [^%&']
T77 ::= [ \n\t]* "```"
""".strip()
preproc_terminal_str = r"""
T0 ::= [ \t\n\r]+
T1 ::= [:_A-Za-z][:_A-Za-z0-9\.\-]*
T2 ::= [:_A-Za-z0-9\.\-]+
T3 ::= '
T4 ::= "
T5 ::= [^<&"]
T6 ::= [^<&']
T7 ::= ((\]\][^>])|[^<&])*
T8 ::= [ \t\n\r]?=[ \t\n\r]?
T9 ::= <
T10 ::= [ \t\n\r]?>
T11 ::= </
T12 ::= [ \t\n\r]?/>
T13 ::= <!\-\-
T14 ::= \-\->
T15 ::= ([^\-]|\-[^\-])*
T16 ::= <\?
T17 ::= \?>
T18 ::= (\?[^>]|[^\?])*
T19 ::= <!\[CDATA\[
T20 ::= \]\]>
T21 ::= ((\]\][^>])|[^\]])*
T22 ::= <\?xml
T23 ::= version
T24 ::= 1\.1
T25 ::= encoding
T26 ::= [A-Za-z][A-Za-z0-9\._\-]*
T27 ::= standalone
T28 ::= yes
T29 ::= no
T30 ::= <!DOCTYPE
T31 ::= \[
T32 ::= \]
T33 ::= %
T34 ::= \&
T35 ::= ;
T36 ::= (\&\#[0-9]+;)|(\&\#x[0-9a-fA-F]+;)
T37 ::= <!ELEMENT
T38 ::= EMPTY
T39 ::= ANY
T40 ::= \(
T41 ::= \)
T42 ::= \|
T43 ::= ,
T44 ::= \?
T45 ::= \*
T46 ::= \+
T47 ::= \#PCDATA
T48 ::= \)\*
T49 ::= <!ATTLIST
T50 ::= CDATA
T51 ::= ID
T52 ::= IDREF
T53 ::= IDREFS
T54 ::= ENTITY
T55 ::= ENTITIES
T56 ::= NMTOKEN
T57 ::= NMTOKENS
T58 ::= NOTATION
T59 ::= \#REQUIRED
T60 ::= \#IMPLIED
T61 ::= \#FIXED
T62 ::= <!ENTITY
T63 ::= SYSTEM
T64 ::= PUBLIC
T65 ::= [^"]*
T66 ::= [^']*
T67 ::= ([ \r\na-zA-Z0-9\-'()+,./:=?;!*#@_%]|\$)*
T68 ::= ([ \r\na-zA-Z0-9\-()+,./:=?;!*#@_%]|\$)*
T69 ::= NDATA
T70 ::= <!NOTATION
T75 ::= [^%&"]
T76 ::= [^%&']
T77 ::= [ \n\t]*```
""".strip()

llguidance_str = ""  # TODO

grammar_spec = GrammarSpec(
    name='xml',
    xgrammar_str=f'{base_nonterminal_str}\n{xgrammar_terminal_str}',
    preprocessing_str=f'{base_nonterminal_str}\nTERMINALS:\n{preproc_terminal_str}',
    llguidance_str = llguidance_str
)
